### ISSUE TITLE
Set https redirection port

### ISSUE THREAD

**Issue by affand** [Polyrific-Inc/Playground-Core#11]
The app use UseHttpsRedirection() to enforce https. However no https port for redirect specified. So we need to add one in Startup.cs

```
services.AddHttpsRedirection(options =>
            {
                options.RedirectStatusCode = StatusCodes.Status307TemporaryRedirect;
                options.HttpsPort = 5001;
            });
```

**Comment by frandi** [comment]
AFAIK, explicit Https port declaration is optional because ASP.Net Core will smartly provide the port for us. If we want to customize the port, I prefer to do it via env var `ASPNETCORE_HTTPS_PORT`.
